FROM golang:1.22.1 AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /projekat

FROM alpine:3.14
COPY --from=build /projekat .
EXPOSE 8080
# Run
CMD ["./projekat"]