version: "3.8"

services:
  server:
    image: jovanovicviktor4701/configuration-server:latest
    restart: always
    container_name: "configuration-server"
    hostname: "configuration-server"
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DB: consul
      DBPORT: 8500
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}
    depends_on:
      - consul
      - jaeger
    networks:
      - monitoring

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - ./consul_store:/consul/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" 
      - "14268:14268"
      - "14250:14250"
      - "6831:6831/udp"
    networks:
      - monitoring

volumes:
  consul:
  prometheus-data:

networks:
  monitoring:
    driver: bridge
