// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/configGroups": {
            "post": {
                "description": "Adds a new configuration group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configGroups"
                ],
                "summary": "Add a new configuration group",
                "parameters": [
                    {
                        "description": "Configuration group to add",
                        "name": "configGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfigGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration group added successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configGroups/{groupName}/{groupVersion}/{configName}/{configVersion}": {
            "delete": {
                "description": "Removes a specific configuration from a specified group",
                "tags": [
                    "configGroups"
                ],
                "summary": "Remove a configuration from a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration group",
                        "name": "groupVersion",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the configuration to remove",
                        "name": "configName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration to remove",
                        "name": "configVersion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration removed from group successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configuration or group not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configGroups/{groupName}/{groupVersion}/{labels}": {
            "get": {
                "description": "Retrieves all configurations within a specific group that match the specified labels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configGroups"
                ],
                "summary": "Retrieve configurations by labels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration group",
                        "name": "groupVersion",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Labels to filter the configurations",
                        "name": "labels",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of configurations",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Config"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid group version",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configurations not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes all configurations within a specific group that match the specified labels",
                "tags": [
                    "configGroups"
                ],
                "summary": "Delete configurations by labels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration group",
                        "name": "groupVersion",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Labels to filter the configurations for deletion",
                        "name": "labels",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configurations deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid group version",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configurations not found for deletion",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configGroups/{name}/{version}": {
            "get": {
                "description": "Retrieves a configuration group by name and version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configGroups"
                ],
                "summary": "Get a configuration group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration group",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration group",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ConfigGroup"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configuration group not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a configuration group by name and version",
                "tags": [
                    "configGroups"
                ],
                "summary": "Delete a configuration group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration group",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration group",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration group deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configuration group not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configGroups/{name}/{version}/configs": {
            "post": {
                "description": "Adds a configuration to a specified group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configGroups"
                ],
                "summary": "Add a configuration to a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration group",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration group",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuration to add to the group",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration added to group successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configuration group not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs": {
            "post": {
                "description": "Adds a new configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Add a new configuration",
                "parameters": [
                    {
                        "description": "Configuration to add",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Config"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs/{name}/{version}": {
            "get": {
                "description": "Retrieves a configuration by name and version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Get a configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Config"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configuration not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a configuration by name and version",
                "tags": [
                    "configs"
                ],
                "summary": "Delete a configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the configuration",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version of the configuration",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted configuration",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Configuration not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Config": {
            "type": "object",
            "properties": {
                "labels": {
                    "description": "Labels are key-value pairs for labeling the configuration\nRequired: true",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "Name of the configuration\nRequired: true",
                    "type": "string"
                },
                "params": {
                    "description": "Parameters are key-value pairs for configuration\nRequired: true",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "version": {
                    "description": "Version of the configuration\nRequired: true",
                    "type": "integer"
                }
            }
        },
        "model.ConfigGroup": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Config"
                    }
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Configuration API",
	Description:      "This is a sample server for a configuration service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
